### ISSUE TITLE
Unable to load Windows tagging script

### ISSUE THREAD

**Issue by maxuyang** [tsngo/stable-diffusion-webui-aesthetic-image-scorer#1]
venv "D:\stable-diffusion-webui\VENV_DIR\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 78d6aef30249530d8cc0b5023b2f8bf8c86f8446
Installing requirements for Web UI
Launching Web UI with arguments: --medvram
Installing pywin32
Aesthetic Image Scorer: Unable to load Windows tagging script
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [40b9da7a] from D:\stable-diffusion-webui\models\Stable-diffusion\ma3.ckpt
Global Step: 487750
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by maxuyang** [comment]
venv "D:\stable-diffusion-webui\VENV_DIR\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 78d6aef30249530d8cc0b5023b2f8bf8c86f8446
Installing requirements for Web UI
Launching Web UI with arguments: --medvram
Installing pywin32
Aesthtic Image Scorer: Forcing prediction model to run on CPU
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [40b9da7a] from D:\stable-diffusion-webui\models\Stable-diffusion\ma3.ckpt
Global Step: 487750
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:14<00:00,  3.52it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 50/50 [00:19<00:00,  2.51it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:11<00:00,  4.32it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 50/50 [00:13<00:00,  3.60it/s]


Save score as EXIF or PNG Info Chunk✔
Save score as tag (Windows Only)✔
Force CPU (Requires Custom Script Reload)✔


No function is added to the web ui interface

**Comment by tsngo** [comment]
check where you put the extension. There should be a tools directory with files in there. If there's no files in tools, delete the extension and run `git clone --recurse-submodules https://github.com/tsngo/stable-diffusion-webui-aesthetic-image-scorer extensions/aesthetic-image-scorer` to pull both this repo and the tools submodule

**Comment by StableInquest** [comment]
Using M1 Mac. Also getting the error:
`Aesthetic Image Scorer: Unable to load Windows tagging script
`

Repo clone was handled correctly.

**Comment by tsngo** [comment]
The code is looking for tools/add_tags.py. Make sure the file is there.

If the file is there then try changing below in image_scorer.py:

`try:
    from tools.add_tags import tag_files
except:
    print("Aesthetic Image Scorer: Unable to load Windows tagging script")
    tag_files = None`

to:

`from tools.add_tags import tag_files`

let me know what the error message is

**Comment by StableInquest** [comment]
Ok that got it to progress to this new error:

```
Error loading script: image_scorer.py
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 157, in load_scripts
    compiled = compile(text, scriptfile.path, 'exec')
  File "/stable-diffusion-webui/extensions/aesthetic-image-scorer/scripts/image_scorer.py", line 23
    state_name = "sac+logos+ava1-l14-linearMSE.pth"
    ^^^^^^^^^^
SyntaxError: expected 'except' or 'finally' block
```

**Comment by tsngo** [comment]
Did you remove `try:` line and also the `except:` the two lines afterwards? That error indicates `try:` is still there.

Replace this entire section

```
try:
    from tools.add_tags import tag_files
except:
    print("Aesthetic Image Scorer: Unable to load Windows tagging script")
    tag_files = None
```

with

```
from tools.add_tags import tag_files
```

This is how it should look afterwards:

```
if platform.system() == "Windows" and not is_installed("pywin32"):
    run_pip(f"install pywin32", "pywin32")

from tools.add_tags import tag_files

state_name = "sac+logos+ava1-l14-linearMSE.pth"
```

**Comment by tsngo** [comment]
Try the latest version and also see https://github.com/tsngo/stable-diffusion-webui-aesthetic-image-scorer/issues/3 for some other issues that you may encounter

**Comment by StableInquest** [comment]
I'm still getting this error. I've deleted and pulled the latest a couple of times and same issue: 
`Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory
`
M1 MacOS

**Comment by TWIISTED-STUDIOS** [comment]
Tried to load this and make the changes you mentioned but still experience the same 
`Aesthetic Image Scorer: Unable to load Windows tagging script`

any updates on this issue?

**Comment by viralhysteria** [comment]
I'm still getting the error regardless of installation method.
