### ISSUE TITLE
Feature request: Option to score and tag existing images.

### ISSUE THREAD

**Issue by LexCybermac** [tsngo/stable-diffusion-webui-aesthetic-image-scorer#2]
Use Case:
Since the release of Stable Diffusion many users have found themselves with folders containing thousands of generated images, with the contents of which often ranging from from jaw-dropping to lacklustre in aesthetic quality. Inevitably as these directories continue to grow users will begin to look to prune them and otherwise whittle them down to what they perceive as just the high quality outputs, a task that could be dramatically optimised with the aid of aesthetic image scoring.

Proposed solution:
I would suggest that such an extension of the WebUI would be integrated as an additional option under the extras tab where there already exists the option to process existing images selected individually, as a group, or from an entire folder. I believe that implementing it under the extras tab would minimise the amount of repeated UI elements and in turn minimise the cluttering of the WebUI.

**Comment by tsngo** [comment]
Not perfect but you could use the Batch Directory under Extra tab to batch all images in a directory. Just turn off upscaling. Any images saved will also contain the score.

**Comment by tsngo** [comment]
I'm unlikely going to implement this given there is the batch directory function available.
