### ISSUE TITLE
A simple walkthrough of File Metadata

### ISSUE THREAD

**Issue by Jonseed** [tsngo/stable-diffusion-webui-aesthetic-image-scorer#8]
I'd like to see the score on PNG files in Windows Explorer. I took a look at File Metadata, and it looks quite complex. A walkthrough of how to use it to show this PNG info would be helpful. Is there a more simple 3rd party software to show this info in Explorer?

**Comment by tsngo** [comment]
Here's a walkthrough: https://www.thewindowsclub.com/enable-tags-for-unsupported-files-windows
